<?php
session_start();
include "../config/db.php";

if (!isset($_SESSION['admin_id'])) {
    header("Location: login.php");
    exit;
}

// Fetch only approved members for the voter list
$members = $conn->query("
    SELECT name, nivasi, avtang, mobile, aadhar_front, aadhar_back 
    FROM members 
    WHERE status = 'approved' 
    ORDER BY nivasi ASC, name ASC
");

?>
<!DOCTYPE html>
<html lang="hi">
<head>
    <meta charset="UTF-8">
    <title>मतदाता सूची - हस्तक्षर</title>
    <style>
        @page {
            size: A4;
            margin: 15mm;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 14px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }
        th, td {
            border: 1px solid #999;
            padding: 8px 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .text-center {
            text-align: center;
        }
        .no-print-btn {
            position: fixed;
            top: 20px;
            right: 20px;
            background: #007bff;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            font-weight: bold;
            box-shadow: 0 2px 5px rgba(0,0,0,0.2);
        }
        .badge {
            font-weight: bold;
            font-size: 11px;
        }
        .badge-success { color: #155724; }
        .badge-danger { color: #721c24; }

        @media print {
            .no-print-btn {
                display: none;
            }
            body {
                background: white;
            }
            th {
                background-color: #f2f2f2 !important;
                -webkit-print-color-adjust: exact;
            }
        }
    </style>
</head>
<body>

    <button class="no-print-btn" onclick="window.print()">📥 Download / Print PDF</button>

    <div class="header">
        <div style="font-size: 16px; font-weight: 500;">सरकार द्वारा मान्यता प्राप्त रजिस्ट्रेशन क्रमांक 685/80-81</div>
        <div style="font-size: 24px; font-weight: 700; margin: 5px 0;">श्री रंकण भवन रांकावत समाज संस्था, रानी स्टे.</div>
        <hr style="border: 1px solid #333; margin: 15px 0;">
        <h2 style="margin: 0; font-size: 20px;">मतदाता सूची (Voter List)</h2>
        <p style="margin: 5px 0 0; font-size: 14px; color: #666;">दिनांक: <?php echo date('d-m-Y'); ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 50px;">क्रमांक</th>
                <th>नाम</th>
                <th>गाँव</th>
                <th>अवटंग</th>
                <th>मोबाइल नंबर</th>
                <th class="text-center">आधार कार्ड</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            if ($members->num_rows > 0):
                $count = 1;
                while ($m = $members->fetch_assoc()):
                    $hasAadhar = (!empty($m['aadhar_front']) || !empty($m['aadhar_back']));
            ?>
                <tr>
                    <td class="text-center"><?php echo $count++; ?></td>
                    <td><?php echo htmlspecialchars($m['name']); ?></td>
                    <td><?php echo htmlspecialchars($m['nivasi']); ?></td>
                    <td><?php echo htmlspecialchars($m['avtang']); ?></td>
                    <td><?php echo htmlspecialchars($m['mobile']); ?></td>
                    <td class="text-center">
                        <?php if ($hasAadhar): ?>
                            <span class="badge badge-success">✔️ Uploaded</span>
                        <?php else: ?>
                            <span class="badge badge-danger">❌ Pending</span>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php 
                endwhile;
            else:
            ?>
                <tr>
                    <td colspan="6" class="text-center">कोई स्वीकृत सदस्य नहीं मिला।</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div style="margin-top: 30px; font-size: 11px; color: #777; text-align: center;">
        Generated by Hastakshar Admin Panel
    </div>

    <script>
        // Optional: Auto trigger print dialog
        // window.onload = function() { window.print(); }
    </script>
</body>
</html>
